const WemillyVarjaoBorges = {
    file:`WemillyVarjaoBorges`,
    title:`Wemilly Varjão Borges`,
    projectLink:`https://www.behance.net/gallery/111774865/Wemilly-Varjao-Borges`,
    platform:`Behance`,
    socialNetworkNamesAndLink:[
        [`instagram`,`https://www.instagram.com/wemilly_v.b/`]
    ],
    imgSrc:[
        `https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/a45b68111774865.600836c472d19.jpg`,
        `https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/c27e82111774865.600836c473bd9.jpg`,
        `https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/d54cec111774865.600836c47474a.jpg`,
        `https://mir-s3-cdn-cf.behance.net/project_modules/fs/87dea6111774865.600b105ac5471.jpg`,
        `https://mir-cdn.behance.net/v1/rendition/project_modules/2800_opt_1/ff9953111774865.600836c475269.jpg`,
        `https://mir-cdn.behance.net/v1/rendition/project_modules/2800_opt_1/8771cc111774865.600836c475c10.jpg`
    ],
    comment:[
        `Suspiras em silêncio e queres que ela te adivinhe. Nunca chegarás ao cabo. Tem-se comparado o amor à guerra. Assim é. No amor, querem-se atos de bravura como na guerra. Avança afoitamente e vencerás.`,
        `Oliveira ouvia estas palavras com a atenção de um homem sem iniciativa, a quem todo conselho serve. Confiava no juízo de Magalhães e o parecer dele era razoável.`,
        `— Parece-te então que eu devo expor-me?`,
        `— Sem dúvida, és um tolo, vês a rapariga num baile, ficas gostando dela, e só porque ela não te caiu logo nos braços, desistes. Oliveira, tem juízo: vai à casa dela, e dir-me-ás daqui a pouco tempo se te não aproveita o conselho. Queres casar, não? `,
        `— Oh! deixei dúvidas?...`,
        `— Não; é uma pergunta.`,
        `No fim de um mês, Oliveira parecia perdido por ela. Magalhães continuava a ser o conselheiro de Oliveira e o seu único confidente. Um dia, pediu-lhe que fosse com ele à casa de Cecília.`,
        `— Tenho medo, disse Magalhães.`,
        `— Por quê?`,
        `— Sou capaz de precipitar tudo, e isso não sei se será conveniente antes de conhecer bem o terreno. Em qualquer caso, não é mau que eu vá examinar por mim mesmo as coisas. Irei quando quiseres.`,
        `— Amanhã?`,
        `— Seja amanhã.`,
        `Na primeira ocasião que se lhe deparou, tratou Magalhães de perscrutar o coração da moça.`,
        `Era de noite; havia gente em casa. Oliveira estava ausente. Magalhães conversava com Cecília a respeito de um chapéu com que uma senhora idosa entrara na sala.`,
        `Magalhães fazia a respeito do chapéu mil conjeturas burlescas.`,
        `— Aquele chapéu, dizia ele, parece-me um ressuscitado. Houve naturalmente alguma epidemia de chapéus em que morreu aquele, acompanhado de outros seus irmãos. Aquele ressuscitou, para vir dizer a este mundo o que é o paraíso dos chapéus.`,
        `Cecília reprimia uma risada.`,
        `Magalhães continuava:`,
        `— Eu, se fosse aquele chapéu, pedia uma pensão como inválido e como raridade.`,
        `Isto era mais burlesco que picante, mais estúrdio que engraçado; todavia, fazia rir Cecília. Repentinamente, Magalhães ficou sério e consultou o relógio.`,
        `— Já se vai embora? perguntou a moça.`,
        `— Não, senhora, disse Magalhães.`,
        `— Guarde então o relógio.`,
        `— Admira-me que Oliveira ainda não viesse.`,
        `— Virá mais tarde. Os senhores são muito amigos?`,
        `— Muito. Conhecemo-nos desde crianças. É uma bela alma.`,
        `Houve um silêncio.`,
        `Magalhães cravou os olhos na moça, que olhava para o chão, e disse:`,
        `— Feliz aquela que o possuir.`,
        `A moça não revelou a menor impressão ao ouvir estas palavras de Magalhães. Ele repetiu a frase, e ela perguntou se não seriam horas de tomar chá.`,
        `— Já amou, D. Cecília? perguntou Magalhães.`,
        `— Que pergunta é essa?`,
        `— É uma curiosidade.`,
        `— Nunca amei.`,
        `— Por quê?`,
        `— Sou muito criança.`,
        `— Criança!`,
        `Outro silêncio.`,
        `— Conheço alguém que a ama muito.`,
        `Cecília estremeceu e ficou muito corada; não respondeu nem se levantou. Para sair, porém, da situação em que as palavras de Magalhães a deixara, disse rindo:`,
        `— Essa pessoa... quem é?`,
        `— Quer saber o nome?`,
        `— Quero. É seu amigo?`,
        `— É.`,
        `— Diga o nome.`,
        `Outro silêncio.`,
        `— Promete não ficar zangada comigo?`,
        `— Prometo.`,
        `— Sou eu.`,
        `Cecília esperava ouvir outra coisa; esperava ouvir o nome de Oliveira. Qualquer que fosse a sua inocência, tinha percebido naqueles últimos dias que o rapaz tinha queda por ela.`,
        `O que eu desejo possuir primeiro é o seu coração. Diga-me: posso esperar essa fortuna?`,
        `— Talvez, murmurou a menina, levantando-se envergonhada dessa singela palavra.`,
        `Minutos depois da cena narrada no capítulo anterior, já os olhos de Cecília procuravam os de Magalhães, mas rapidamente, sem se demorar neles; todos os sintomas de um coração que não se demorará em ceder. `,
        `-`,
        `Almas Agradecidas - Machado de Assis`,
    ]
};
export default WemillyVarjaoBorges;